version: 2

build:
  os: ubuntu-22.04
  tools:
    python:
      version: "3.11"

sphinx:
  configuration: docs/sphinx/conf.py
  builder: html

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
